"""initial migration

Revision ID: 1a2cfd69d148
Revises: 
Create Date: 2024-03-11 11:07:02.488772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2cfd69d148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financialplanning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('employment', sa.String(length=100), nullable=False),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financialplanning')
    # ### end Alembic commands ###
