"""update database

Revision ID: 3162b59677b2
Revises: 
Create Date: 2024-03-13 10:56:29.532548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3162b59677b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('cover_type', sa.String(length=100), nullable=False),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financialplanning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('employment', sa.String(length=100), nullable=False),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('no_children', sa.Integer(), nullable=False),
    sa.Column('solution', sa.String(length=100), nullable=False),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('cover_type', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('cover_type', sa.String(length=100), nullable=False),
    sa.Column('year_manufc', sa.String(length=10), nullable=False),
    sa.Column('valuation', sa.Integer(), nullable=True),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motors')
    op.drop_table('medical')
    op.drop_table('investment')
    op.drop_table('financialplanning')
    op.drop_table('corporate')
    # ### end Alembic commands ###
