"""add medical model

Revision ID: 361dc10c7507
Revises: 784cc7923465
Create Date: 2024-03-13 08:35:36.880947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361dc10c7507'
down_revision = '784cc7923465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.drop_column('cover_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
