"""upgrade table migration

Revision ID: 75b1ce32bac8
Revises: e9f5143e7b8a
Create Date: 2024-04-06 14:23:12.996667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b1ce32bac8'
down_revision = 'e9f5143e7b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_dob', sa.Date(), nullable=False))
        batch_op.drop_column('no_children')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_children', sa.INTEGER(), nullable=False))
        batch_op.drop_column('principal_dob')

    # ### end Alembic commands ###
