"""add motor model

Revision ID: 91e111ca28c8
Revises: df7397cf6646
Create Date: 2024-03-12 16:49:03.619767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e111ca28c8'
down_revision = 'df7397cf6646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('cover_type', sa.String(length=100), nullable=False),
    sa.Column('year_manufc', sa.String(length=10), nullable=False),
    sa.Column('valuation', sa.Integer(), nullable=True),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motors')
    # ### end Alembic commands ###
