"""investment table

Revision ID: df7397cf6646
Revises: 1a2cfd69d148
Create Date: 2024-03-12 01:03:33.430755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7397cf6646'
down_revision = '1a2cfd69d148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('no_children', sa.Integer(), nullable=False),
    sa.Column('solution', sa.String(length=100), nullable=False),
    sa.Column('meeting', sa.String(length=100), nullable=False),
    sa.Column('app_date', sa.Date(), nullable=False),
    sa.Column('app_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment')
    # ### end Alembic commands ###
